import type { CSSProperties } from "react";

export const s = {
  layout: { display: "flex", height: "100%", minHeight: 0 } satisfies CSSProperties,
  side: { width: 300, borderRight: "1px solid var(--border)", display: "flex", flexDirection: "column" } satisfies CSSProperties,
  sideHead: { padding: "16px 16px 8px" } satisfies CSSProperties,
  eyebrow: { fontSize: 11, letterSpacing: "0.06em", textTransform: "uppercase", color: "var(--text-muted)", fontWeight: 600 } satisfies CSSProperties,
  folders: { fontSize: 12, color: "var(--text-secondary)", marginTop: 2 } satisfies CSSProperties,
  actions: { display: "flex", gap: 6, marginTop: 10 } satisfies CSSProperties,
  list: { listStyle: "none", margin: 0, padding: "0 8px", overflow: "auto", flex: 1 } satisfies CSSProperties,
  item: (active: boolean): CSSProperties => ({
    display: "flex",
    alignItems: "center",
    gap: 8,
    width: "100%",
    padding: "8px 10px",
    borderRadius: 7,
    border: "none",
    background: active ? "var(--bg-hover)" : "transparent",
    color: "var(--text-primary)",
    textAlign: "left",
    cursor: "pointer",
    fontSize: 13,
  }),
  itemMeta: { marginLeft: "auto", fontSize: 11, color: "var(--text-muted)" } satisfies CSSProperties,
  sideFoot: { padding: "10px 16px", borderTop: "1px solid var(--border)", fontSize: 11, color: "var(--text-muted)" } satisfies CSSProperties,
  main: { flex: 1, minWidth: 0, display: "flex", flexDirection: "column" } satisfies CSSProperties,
  mainHead: { display: "flex", alignItems: "center", gap: 12, padding: "12px 24px", borderBottom: "1px solid var(--border)" } satisfies CSSProperties,
  segmented: { display: "inline-flex", border: "1px solid var(--border)", borderRadius: 7, overflow: "hidden" } satisfies CSSProperties,
  seg: (on: boolean): CSSProperties => ({
    padding: "4px 12px",
    fontSize: 12,
    border: "none",
    background: on ? "var(--bg-hover)" : "transparent",
    color: on ? "var(--text-primary)" : "var(--text-muted)",
    cursor: "pointer",
  }),
  headRight: { marginLeft: "auto", display: "flex", alignItems: "center", gap: 12, fontSize: 12, color: "var(--text-muted)" } satisfies CSSProperties,
  body: { padding: "20px 24px", overflow: "auto", flex: 1, fontSize: 14 } satisfies CSSProperties,
  textarea: {
    width: "100%",
    minHeight: 360,
    padding: 12,
    borderRadius: 8,
    border: "1px solid var(--border-strong)",
    background: "var(--bg-elevated)",
    color: "inherit",
    fontSize: 13,
  } satisfies CSSProperties,
  editFoot: { display: "flex", alignItems: "center", gap: 10, marginTop: 10 } satisfies CSSProperties,
  caveat: { marginTop: 10, fontSize: 13, color: "var(--text-secondary)" } satisfies CSSProperties,
  warn: { marginTop: 10, fontSize: 13, color: "var(--warn, #d9a300)" } satisfies CSSProperties,
  error: { marginTop: 10, fontSize: 13, color: "var(--crit)" } satisfies CSSProperties,
  dialogBody: { display: "flex", flexDirection: "column", gap: 14 } satisfies CSSProperties,
  dialogFoot: { display: "flex", justifyContent: "flex-end", gap: 8 } satisfies CSSProperties,
  select: { width: "100%", padding: "8px 10px", borderRadius: 7, border: "1px solid var(--border-strong)", background: "var(--bg-elevated)", color: "inherit" } satisfies CSSProperties,
  center: { padding: 24 } satisfies CSSProperties,
} as const;
