import type { CSSProperties } from "react";

export const s = {
  wrap: { padding: "20px 24px", display: "flex", flexDirection: "column", gap: 12 } satisfies CSSProperties,
  head: { display: "flex", alignItems: "center", gap: 10 } satisfies CSSProperties,
  title: { fontSize: 16, fontWeight: 650 } satisfies CSSProperties,
  filter: { marginLeft: "auto", width: 240 } satisfies CSSProperties,
  note: { fontSize: 13, color: "var(--text-secondary)" } satisfies CSSProperties,
  list: { display: "flex", flexDirection: "column", gap: 8, listStyle: "none", margin: 0, padding: 0 } satisfies CSSProperties,
  row: {
    border: "1px solid var(--border)",
    borderRadius: 8,
    background: "var(--bg-elevated)",
    padding: "8px 12px",
  } satisfies CSSProperties,
  rowMain: { display: "flex", alignItems: "center", gap: 10 } satisfies CSSProperties,
  folder: { fontSize: 12, color: "var(--text-muted)" } satisfies CSSProperties,
  rowRight: { marginLeft: "auto", display: "flex", alignItems: "center", gap: 6 } satisfies CSSProperties,
  miniBtn: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
    padding: "3px 8px",
    borderRadius: 6,
    border: "1px solid var(--border)",
    background: "transparent",
    color: "var(--text-secondary)",
    fontSize: 12,
    cursor: "pointer",
  } satisfies CSSProperties,
  previewBox: {
    marginTop: 8,
    padding: 10,
    borderTop: "1px solid var(--border)",
    fontSize: 13,
    maxHeight: 260,
    overflow: "auto",
  } satisfies CSSProperties,
  footer: { display: "flex", alignItems: "center", gap: 12, fontSize: 12, color: "var(--text-muted)" } satisfies CSSProperties,
  warn: { color: "var(--warn, #d9a300)", fontSize: 13 } satisfies CSSProperties,
  error: { color: "var(--crit)", fontSize: 13 } satisfies CSSProperties,
  srOnly: {
    position: "absolute",
    width: 1,
    height: 1,
    overflow: "hidden",
    clip: "rect(0 0 0 0)",
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
  serializesLabel: { fontSize: 11, letterSpacing: "0.06em", textTransform: "uppercase", color: "var(--text-muted)", marginTop: 8 } satisfies CSSProperties,
  pre: {
    margin: 0,
    padding: 12,
    border: "1px solid var(--border)",
    borderRadius: 8,
    background: "var(--bg-elevated)",
    fontSize: 12,
    whiteSpace: "pre-wrap",
    maxHeight: 260,
    overflow: "auto",
  } satisfies CSSProperties,
} as const;
