import type { CSSProperties } from "react";

export const s = {
  card: {
    border: "1px solid var(--border)",
    borderRadius: 8,
    background: "var(--bg-elevated)",
    padding: 18,
    display: "flex",
    flexDirection: "column",
    gap: 16,
  } satisfies CSSProperties,
  header: { display: "flex", alignItems: "center", gap: 8, flexWrap: "wrap" } satisfies CSSProperties,
  actions: { marginLeft: "auto", display: "flex", alignItems: "center", gap: 8 } satisfies CSSProperties,
  muted: { fontSize: 12.5, color: "var(--text-muted)" } satisfies CSSProperties,
  empty: {
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
    gap: 10,
    fontSize: 14,
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  summary: { fontSize: 14.5, lineHeight: 1.6, color: "var(--text-primary)", margin: 0 } satisfies CSSProperties,
  notice: {
    fontSize: 12.5,
    padding: "6px 10px",
    borderRadius: 6,
    background: "var(--warn-bg)",
    color: "var(--warn)",
  } satisfies CSSProperties,
  error: {
    fontSize: 13,
    padding: "8px 12px",
    borderRadius: 6,
    background: "var(--crit-bg)",
    color: "var(--crit)",
    display: "flex",
    alignItems: "center",
    gap: 10,
  } satisfies CSSProperties,
  aside: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(300px, 1fr))", gap: 20 } satisfies CSSProperties,
  asideCell: { minWidth: 0 } satisfies CSSProperties,
  heading: {
    fontSize: 12,
    fontWeight: 700,
    letterSpacing: "0.04em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
    margin: "0 0 8px",
  } satisfies CSSProperties,
  list: { listStyle: "none", margin: 0, padding: 0, display: "flex", flexDirection: "column", gap: 6 } satisfies CSSProperties,
  riskRow: { display: "flex", alignItems: "center", gap: 8, width: "100%", background: "none", border: 0, padding: "4px 0", cursor: "pointer", textAlign: "left", color: "inherit", font: "inherit" } satisfies CSSProperties,
  riskTitle: { fontSize: 14, fontWeight: 600 } satisfies CSSProperties,
  riskExplanation: { margin: "2px 0 6px 26px", fontSize: 13.5, lineHeight: 1.55, color: "var(--text-secondary)" } satisfies CSSProperties,
  file: { fontSize: 12.5, color: "var(--text-muted)" } satisfies CSSProperties,
  focusItem: { display: "flex", alignItems: "baseline", gap: 8, width: "100%", background: "none", border: 0, padding: "4px 0", cursor: "pointer", textAlign: "left", color: "inherit", font: "inherit" } satisfies CSSProperties,
  focusFile: { fontSize: 13, color: "var(--accent-text, var(--accent))", flexShrink: 0 } satisfies CSSProperties,
  focusReason: { fontSize: 13.5, color: "var(--text-secondary)" } satisfies CSSProperties,
  ordinal: { fontSize: 12, color: "var(--text-muted)", width: 16, flexShrink: 0 } satisfies CSSProperties,
} as const;
